services:
  server:
    image: kanban-app-backend-prod
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: kanban-app-backend-prod
    

  nginx:
    image: kanban-app-reverse-proxy-prod
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: kanban-app-reverse-proxy-prod
    depends_on:
      - server